version: '3.7'

services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
        - ${TCP_PORT:-9001}:9001

volumes:
  portainer_data:
