version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
        - ${HTTP_PORT:-8000}:8000
        - ${HTTPS_PORT:-9443}:9443

volumes:
  portainer_data:
